### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kvarys** [yycdavid/program-synthesis-guided-RL#2]
Dear Researchers,

I was looking for your code's license but did not find one in the repository. Is it possible you have forgotten to specify it?

If the license is there and I missed it, please accept my apologies. In that case could you please send me the link to the license?

Thank you!

**Comment by yycdavid** [comment]
Thank you for noticing! I've added a MIT license. Will close this issue now but let me know if you have other questions! Thanks for the interest!
